import './EscrowPolicy.css';

const EscrowPolicy: React.FC = () => {
  return (
    <div className="escrow-container">
      <div className="escrow-header">
        <h1>UNISWAPNG ESCROW POLICY</h1>
        <p className="last-updated">Last Updated: December 2025</p>
      </div>

      <div className="escrow-content">
        <div className="escrow-intro">
          <p>
            This Escrow Policy ("Policy") sets forth the terms and conditions governing the optional escrow functionality ("Escrow Service") made available by Uniswapng ("Uniswapng", "we", "our", or "us"). This Policy forms an integral part of, and is hereby incorporated by reference into, the Uniswapng Terms and Conditions ("Terms"). Capitalised terms not otherwise defined herein shall bear the meanings ascribed to them under the Terms.
          </p>
          <p>
            By electing to utilise the Escrow Service, the User expressly acknowledges and agrees to be bound by the provisions contained herein.
          </p>
        </div>

        <section className="escrow-section">
          <h2>1. DEFINITIONS</h2>
          <p>For purposes of this Policy:</p>
          <div className="definition-list">
            <div className="definition-item">
              <h4>1.1 "Buyer"</h4>
              <p>means the User initiating an escrow-enabled transaction for the purchase of goods or services.</p>
            </div>

            <div className="definition-item">
              <h4>1.2 "Seller"</h4>
              <p>means the User accepting an Escrow Request and undertaking to deliver the corresponding goods or services.</p>
            </div>

            <div className="definition-item">
              <h4>1.3 "Swap Code"</h4>
              <p>means the unique alphanumeric code generated by the Platform for each escrow transaction, the valid entry of which by the Seller constitutes conclusive authorisation for the release of funds.</p>
            </div>

            <div className="definition-item">
              <h4>1.4 "Payment Partner"</h4>
              <p>means the duly authorised third-party financial institution or payments processor that maintains custody of User funds and effects all settlement activities.</p>
            </div>

            <div className="definition-item">
              <h4>1.5 "Escrow Request"</h4>
              <p>means a Buyer-initiated invitation to a Seller to transact pursuant to this Policy.</p>
            </div>

            <div className="definition-item">
              <h4>1.6 "Escrow Window"</h4>
              <p>means the twenty-four (24) hour period commencing upon the Seller's acceptance of the Escrow Request, within which the transaction must be completed.</p>
            </div>

            <div className="definition-item">
              <h4>1.7 "Wallet"</h4>
              <p>means the custodial virtual account assigned to each User and operated exclusively by the Payment Partner.</p>
            </div>
          </div>
        </section>

        <section className="escrow-section">
          <h2>2. NATURE OF THE ESCROW SERVICE</h2>
          <div className="subsection">
            <h4>2.1</h4>
            <p>The Escrow Service is an optional facilitative mechanism designed to enhance transactional safety between Users. Its utilisation is neither mandatory nor automatic.</p>
          </div>

          <div className="subsection">
            <h4>2.2</h4>
            <p>Uniswapng is not a party to any transaction conducted between Users and does not assume any fiduciary, trustee, agency, or custodial obligations in respect of the Escrow Service.</p>
          </div>

          <div className="subsection">
            <h4>2.3</h4>
            <p>Funds associated with escrow transactions are not held by Uniswapng at any time. Custody, safekeeping, and settlement of all funds are undertaken solely by the Payment Partner pursuant to its regulatory authorisations.</p>
          </div>
        </section>

        <section className="escrow-section">
          <h2>3. CONDITIONS PRECEDENT TO ESCROW</h2>
          <p>Escrow may be utilised only where:</p>
          <div className="subsection">
            <h4>3.1</h4>
            <p>the Buyer possesses sufficient cleared Wallet funds to support the contemplated transaction;</p>
          </div>

          <div className="subsection">
            <h4>3.2</h4>
            <p>the Buyer initiates an Escrow Request;</p>
          </div>

          <div className="subsection">
            <h4>3.3</h4>
            <p>the Seller affirmatively accepts the Escrow Request within the Acceptance Window defined below; and</p>
          </div>

          <div className="subsection">
            <h4>3.4</h4>
            <p>the transaction does not pertain to event ticket purchases, which are expressly excluded from the Escrow Service.</p>
          </div>
        </section>

        <section className="escrow-section">
          <h2>4. INITIATION AND ACCEPTANCE</h2>
          <div className="subsection">
            <h4>4.1</h4>
            <p>Upon a Buyer's submission of an Escrow Request, no funds shall be locked, reserved, or otherwise encumbered unless and until the Seller elects to accept the request.</p>
          </div>

          <div className="subsection">
            <h4>4.2</h4>
            <p>The Seller shall have one (1) hour from the issuance of the Escrow Request ("Acceptance Window") to accept same. Failure to accept within the Acceptance Window shall result in automatic lapse of the Escrow Request, without any obligation or consequence to either party.</p>
          </div>

          <div className="subsection">
            <h4>4.3</h4>
            <p>No escrow transaction shall be deemed to have commenced, nor shall any Escrow Window begin to run, unless the Seller has accepted the Escrow Request in accordance with this Clause.</p>
          </div>
        </section>

        <section className="escrow-section highlight-section">
          <h2>5. COMMENCEMENT OF ESCROW</h2>
          <div className="subsection">
            <h4>5.1</h4>
            <p>Upon acceptance by the Seller:</p>
            <ul>
              <li>(a) the Buyer's Wallet funds equivalent to the transaction value shall be locked and reflected as "processing to go out";</li>
              <li>(b) a corresponding pending credit shall be reflected to the Seller as "processing to come in"; and</li>
              <li>(c) the Escrow Window of twenty-four (24) hours shall commence forthwith.</li>
            </ul>
          </div>

          <div className="subsection">
            <h4>5.2</h4>
            <p>Escrow shall be deemed active only from this moment, and all obligations of the parties hereunder shall attach accordingly.</p>
          </div>
        </section>

        <section className="escrow-section highlight-section">
          <h2>6. COMPLETION MECHANISM (SWAP CODE)</h2>
          <div className="subsection">
            <h4>6.1</h4>
            <p>Completion of the escrow transaction is strictly contingent upon the Seller's valid entry of the Swap Code.</p>
          </div>

          <div className="subsection">
            <h4>6.2</h4>
            <p>The Buyer must conduct all inspections, verifications, and assessments of the goods or services prior to releasing the Swap Code. The provision of the Swap Code constitutes the Buyer's final, irrevocable confirmation of satisfaction.</p>
          </div>

          <div className="subsection">
            <h4>6.3</h4>
            <p>The Seller shall not deliver or part with possession of any goods or perform any services until the Swap Code has been disclosed to them. Any premature delivery is undertaken at the Seller's sole risk.</p>
          </div>

          <div className="subsection">
            <h4>6.4</h4>
            <p>Upon the Seller's valid entry of the Swap Code:</p>
            <ul>
              <li>(a) escrow shall be deemed conclusively completed;</li>
              <li>(b) funds shall be released to the Seller; and</li>
              <li>(c) the transaction shall attain finality, subject only to the limited appeal provisions herein.</li>
            </ul>
          </div>
        </section>

        <section className="escrow-section">
          <h2>7. EXPIRY, NON-COMPLETION & REFUNDS</h2>
          <div className="subsection">
            <h4>7.1</h4>
            <p>Should the Seller fail to enter the Swap Code within the Escrow Window, the escrow transaction shall automatically terminate and the locked funds shall, without further action, be refunded to the Buyer.</p>
          </div>

          <div className="subsection">
            <h4>7.2</h4>
            <p>Where the Buyer elects not to release the Swap Code for any reason, escrow shall remain pending until expiry of the Escrow Window, at which point funds shall automatically revert to the Buyer.</p>
          </div>

          <div className="subsection">
            <h4>7.3</h4>
            <p>Either party may cancel the escrow transaction at any time prior to Swap Code entry. All such cancellations shall result in automatic refund to the Buyer.</p>
          </div>

          <div className="subsection">
            <h4>7.4</h4>
            <p>Any Swap Code entered after expiry of the Escrow Window shall be deemed void and shall have no effect.</p>
          </div>
        </section>

        <section className="escrow-section">
          <h2>8. APPEALS (LIMITED SCOPE)</h2>
          <div className="subsection">
            <h4>8.1</h4>
            <p>Appeals may be lodged only in respect of completed transactions, i.e., where the Swap Code has been entered and funds discharged to the Seller.</p>
          </div>

          <div className="subsection">
            <h4>8.2</h4>
            <p>Any appeal must be submitted within twenty-four (24) hours of Swap Code entry. Appeals submitted outside this period shall be summarily rejected.</p>
          </div>

          <div className="subsection">
            <h4>8.3</h4>
            <p>Appeals must be addressed to <a href="mailto:support@uniswapng.com">support@uniswapng.com</a> and accompanied by substantiating evidence, including but not limited to photographs, videos, transaction screenshots, conversations, or proof of defect or misrepresentation.</p>
          </div>

          <div className="subsection">
            <h4>8.4</h4>
            <p>Uniswapng's review of appeals is administrative, discretionary, and non-binding, and shall not constitute formal dispute resolution or adjudication.</p>
          </div>

          <div className="subsection">
            <h4>8.5</h4>
            <p>Appeals shall not delay, suspend, or reverse any automatic processes under this Policy, including the expiry of the Escrow Window or the operation of refund mechanisms.</p>
          </div>
        </section>

        <section className="escrow-section warning-section">
          <h2>9. PROHIBITED APPLICATIONS</h2>
          <p>The Escrow Service shall not be utilised for:</p>
          <div className="prohibited-list">
            <div className="prohibited-item">
              <h4>9.1</h4>
              <p>transactions involving event tickets;</p>
            </div>

            <div className="prohibited-item">
              <h4>9.2</h4>
              <p>transactions conducted outside the Platform;</p>
            </div>

            <div className="prohibited-item">
              <h4>9.3</h4>
              <p>unlawful, fraudulent, misleading, or prohibited items or activities;</p>
            </div>

            <div className="prohibited-item">
              <h4>9.4</h4>
              <p>transactions requiring partial, milestone, or multi-stage payments;</p>
            </div>

            <div className="prohibited-item">
              <h4>9.5</h4>
              <p>transactions where Wallet funds are insufficient or uncleared.</p>
            </div>
          </div>
        </section>

        <section className="escrow-section">
          <h2>10. FEES</h2>
          <div className="subsection">
            <h4>10.1</h4>
            <p>Uniswapng presently imposes no charges for the utilisation of the Escrow Service.</p>
          </div>

          <div className="subsection">
            <h4>10.2</h4>
            <p>Fees may be applicable for Wallet funding or other financial operations conducted by the Payment Partner.</p>
          </div>

          <div className="subsection">
            <h4>10.3</h4>
            <p>Uniswapng reserves the right to introduce escrow-related fees in the future, subject to prior notice in accordance with the Terms.</p>
          </div>
        </section>

        <section className="escrow-section">
          <h2>11. ROLE AND LIMITATION OF LIABILITY OF UNISWAPNG</h2>
          <div className="subsection">
            <h4>11.1</h4>
            <p>Uniswapng acts solely as a technical facilitator of the Escrow Service and does not assume responsibility for:</p>
            <ul>
              <li>(a) the existence, quality, legality, safety, or condition of any goods or services;</li>
              <li>(b) Users' performance or non-performance of obligations;</li>
              <li>(c) accuracy or completeness of User listings or representations;</li>
              <li>(d) the conduct of Users during in-person interactions; or</li>
              <li>(e) the custody, transfer, or settlement of funds, which are effected exclusively by the Payment Partner.</li>
            </ul>
          </div>

          <div className="subsection">
            <h4>11.2</h4>
            <p>Uniswapng shall not be liable for any indirect, consequential, punitive, exemplary, or special damages arising from or in connection with the Escrow Service.</p>
          </div>

          <div className="subsection">
            <h4>11.3</h4>
            <p>Users transact entirely at their own risk, and each User indemnifies Uniswapng from all claims, losses, or liabilities arising from their use of the Escrow Service.</p>
          </div>
        </section>

        <section className="escrow-section">
          <h2>12. FRAUD, ABUSE & SUSPENSION</h2>
          <div className="subsection">
            <h4>12.1</h4>
            <p>Uniswapng may, in its sole discretion, suspend or terminate a User's access to the Escrow Service where misuse, circumvention, fraud, or breach of this Policy is suspected.</p>
          </div>

          <div className="subsection">
            <h4>12.2</h4>
            <p>Uniswapng may report suspicious activity to competent authorities as required by law.</p>
          </div>
        </section>

        <section className="escrow-section">
          <h2>13. AMENDMENT, SEVERABILITY & SURVIVAL</h2>
          <div className="subsection">
            <h4>13.1</h4>
            <p>Uniswapng may amend this Policy at any time pursuant to the Terms. Continued use of the Escrow Service constitutes acceptance of any amended Policy.</p>
          </div>

          <div className="subsection">
            <h4>13.2</h4>
            <p>If any provision herein is held unenforceable, such provision shall be severed without affecting the enforceability of the remainder.</p>
          </div>

          <div className="subsection">
            <h4>13.3</h4>
            <p>Clauses relating to limitation of liability, indemnity, and governing law shall survive termination or completion of any escrow transaction.</p>
          </div>
        </section>

        <section className="escrow-section final-section">
          <h2>14. GOVERNING LAW AND JURISDICTION</h2>
          <p>
            This Policy shall be governed by, and construed in accordance with, the laws of the Federal Republic of Nigeria. The courts of Lagos State, Nigeria shall have exclusive jurisdiction over all disputes arising hereunder.
          </p>
        </section>

        <footer className="escrow-footer">
          <p>© 2025 Uniswap NG. All rights reserved.</p>
          <p>This Escrow Policy is effective as of December 2025.</p>
        </footer>
      </div>
    </div>
  );
};

export default EscrowPolicy;
